apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: short-api
    template:
        metadata:
            labels:
                app: short-api
        spec:
            containers:
                - name: api
                  image: antonlarichev/short-api:v1.0
                  ports:
                     - containerPort: 3000
                  resources:
                    limits:
                      memory: "500Mi"  # Adjust the value as needed
                      cpu: "300m"
                  env:
                    - name: DATABASE_URL
                      valueFrom:
                        secretKeyRef:
                          name: short-api-secret
                          key: DATABASE_URL
                  volumeMounts:
                    - name: api-data
                      mountPath: /etc/test
                      readOnly: true
                  livenessProbe:
                    exec:
                      command:
                        - curl
                        - --fail
                        - http://localhost:3000/api
                    initialDelaySeconds: 30
                    periodSeconds: 5
                    failureThreshold: 1
            volumes:
                - name: api-data
                  configMap:
                    name: short-api-config
