apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short-app  # This should match the labels in the Pod template
  template:
    metadata:
      labels:
        app: short-app  # Labels used for Pod selection
    spec:
      containers:
        - name: short-app
          image: antonlarichev/short-app:v1.4
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
