{{- range $index, $api := .Values.api }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $api.name }}-secret
type: Opaque
{{- end }}
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-clusterip:%d/%s"
  .Values.database.user
  .Values.database.password
  .Values.apps.postgres.name
  (.Values.apps.postgres.port | int64 )
  .Values.database.db  | b64enc | quote }}