{{- range $index, $api := .Values.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $api.containerName }}-clusterip
spec:
  type: ClusterIP
  selector:
    app: {{ $api.name }}
  ports:
    - port: {{ $api.port }}
      protocol: TCP
{{- end}}