apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: short-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: demo.test
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.apps.app.name }}-clusterip
            port:
              number: {{ .Values.apps.app.port }}
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: {{ .Values.apps.api.containerName }}-clusterip
            port:
              number: {{ .Values.apps.api.port }}