apiVersion: v1
kind: Service
metadata:
  name: short-app-port
  labels:
    app: node-port
spec:
    type: NodePort
    selector:
        app: short-app
    ports:
        - port: 3000
          nodePort: 30125
          targetPort: 80